//
//  FixtureCatalog.swift
//  DownloadKitSample
//
//  The files the fixture server generates (sizes and SHA-256 as recorded in
//  sample/fixture-server/Sources/FixtureServer/Fixtures.swift) and one item per response
//  scenario. Nothing here is real content.
//

import Foundation

struct FixtureFile: Hashable, Sendable {
    let name: String
    let length: Int64
    let sha256: String

    static let toneA = FixtureFile(name: "tone-a.wav", length: 132_344, sha256: "751cff056f4961db52e34a8b30075cb16ae0464c8b70190e49cf4ef847ee916e")
    static let toneB = FixtureFile(name: "tone-b.wav", length: 132_344, sha256: "c840066afbf14bba502be81512787a991c9f3f506df1a9522df219b4f54adb93")
    static let toneC = FixtureFile(name: "tone-c.wav", length: 132_344, sha256: "77b1569c744e52ce6e53ae122a1fde23c256c09bb0ea4ffdd3b14d261f216172")
    static let longTone = FixtureFile(name: "long-tone.wav", length: 2_646_044, sha256: "b8ba52028bcbe09f8888a2a56a14a74f965a37534777bbbf2b72603e103cbf31")
    static let large = FixtureFile(name: "large.bin", length: 25_165_824, sha256: "69e31f4f29cc93bca1b122c6ecd43f58c162700cc0d59a5f7eacfbd1e86649d8")

    static let all: [FixtureFile] = [.toneA, .toneB, .toneC, .longTone, .large]
}

struct FixtureItem: Identifiable, Hashable, Sendable {
    let id: String
    let title: String
    let subtitle: String
    let group: String
    /// Path below the server's base URL.
    let path: String
    let file: FixtureFile
    /// Whether the request tells the package the expected length (and so the progress total).
    let declaresLength: Bool
    /// Whether the file can be played (WAV) once downloaded.
    var isAudio: Bool { file.name.hasSuffix(".wav") }
}

/// The response scenarios the fixture server implements (mirrors its `Scenario` type).
enum FixtureScenario: String, CaseIterable, Identifiable, Sendable {
    case ok
    case ignoreRange = "ignore-range"
    case rangeNotSatisfiable = "range-416"
    case changingETag = "changing-etag"
    case redirect
    case noLength = "no-length"
    case slowFirstByte = "slow-first-byte"
    case slowBody = "slow-body"
    case disconnect
    case truncated
    case notFound = "not-found"
    case serverError = "server-error"
    case unavailable
    case html
    case htmlAsMedia = "html-as-media"
    case checksumMismatch = "checksum-mismatch"
    case expired
    case unauthorized

    var id: String { rawValue }

    var summary: String {
        switch self {
        case .ok: return "200, ranges answered with 206"
        case .ignoreRange: return "200 even for a range request"
        case .rangeNotSatisfiable: return "416 for any range request"
        case .changingETag: return "New ETag on every response"
        case .redirect: return "302 to the plain file"
        case .noLength: return "No Content-Length: indeterminate progress"
        case .slowFirstByte: return "8 s before the first byte"
        case .slowBody: return "64 KiB per second: time to pause"
        case .disconnect: return "Connection reset after 40%: retried"
        case .truncated: return "Body 1 KiB short: retried"
        case .notFound: return "404: fails, no retry"
        case .serverError: return "500 with Retry-After 3: retried"
        case .unavailable: return "503 with Retry-After 10: retried"
        case .html: return "An HTML page: refused"
        case .htmlAsMedia: return "HTML declared as audio: refused"
        case .checksumMismatch: return "One byte changed: integrity failure"
        case .expired: return "403 expired link: retry refreshes it"
        case .unauthorized: return "401: authentication failure"
        }
    }
}

enum FixtureCatalog {
    static let items: [FixtureItem] = media + scenarios

    static let media: [FixtureItem] = [
        FixtureItem(id: "tone-a", title: "Tone A", subtitle: "440 Hz, 3 seconds", group: "Tones", path: "files/tone-a.wav", file: .toneA, declaresLength: true),
        FixtureItem(id: "tone-b", title: "Tone B", subtitle: "660 Hz, 3 seconds", group: "Tones", path: "files/tone-b.wav", file: .toneB, declaresLength: true),
        FixtureItem(id: "tone-c", title: "Tone C", subtitle: "880 Hz, 3 seconds", group: "Tones", path: "files/tone-c.wav", file: .toneC, declaresLength: true),
        FixtureItem(id: "long-tone", title: "Long tone", subtitle: "220 Hz, 60 seconds", group: "Tones", path: "files/long-tone.wav", file: .longTone, declaresLength: true),
        FixtureItem(id: "large", title: "Large file", subtitle: "24 MiB of generated bytes", group: "Large files", path: "files/large.bin", file: .large, declaresLength: true),
    ]

    static let scenarios: [FixtureItem] = FixtureScenario.allCases.filter { $0 != .ok }.map { scenario in
        FixtureItem(
            id: "scenario-" + scenario.rawValue,
            title: scenario.rawValue,
            subtitle: scenario.summary,
            group: "Scenarios",
            path: "s/\(scenario.rawValue)/tone-a.wav",
            file: .toneA,
            declaresLength: scenario != .noLength
        )
    }

    static func item(_ id: String) -> FixtureItem? {
        items.first { $0.id == id }
    }
}
